services:
  - type: web
    name: reviewxpress-saas
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
      - key: GEMINI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: "ReviewXpress <noreply@reviewxpress.in>"
      - key: EMAIL_USER
        value: botmate.in@gmail.com
      - key: EMAIL_PASS
        value: wcvmiginkraahyxj
      - key: NEXT_PUBLIC_TURNSTILE_SITE_KEY
        sync: false
      - key: TURNSTILE_SECRET_KEY
        sync: false
